version: '3'
services:
  user_service:
    build:
      context: ./user_service
    ports:
      - "8081:8081"

  order_service:
    build:
      context: ./order_service
    ports:
      - "8082:8082"
    depends_on:
      - user_service
