version: '3'
services:
  user-service:
    build:
      context: ./path/to/user-service
    ports:
      - "8081:8081"

  order-service:
    build:
      context: ./path/to/order-service
    ports:
      - "8082:8082"
    depends_on:
      - user-service
